title: VIS 42
description: A foundational course on programming and computational thinking in the arts.
theme: just-the-docs

url: https://roberttwomey.github.io/vis42-fall2025/

aux_links:
  Canvas: [TK]
