title: Intro to Creative Code
description: A foundational course on programming and computational thinking in the arts.
theme: just-the-docs

url: https://roberttwomey.github.io/vis42-fall2025/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
